-- VFN_DecorVendorsDB.lua -- GENERATED by vfn-tools/build_decor_vendor_seed.py
-- Source: HousingDecorGuide/data/HDG_VendorDB.lua
-- Built:  2026-05-11 23:29:17
-- DO NOT EDIT MANUALLY -- regenerate with:
--   python3 vfn-tools/build_decor_vendor_seed.py

VFN_DecorVendorsDB = {
    libraryName = "Decor Vendors",
    zones = {
        {
            zone = "Acherus",
            vendors = {
                { name = "Quartermaster Ozorg", mapID = 647, x = 43.9, y = 37.2, faction = "N" },
            },
        },
        {
            zone = "Arcantina",
            vendors = {
                { name = "Morta Gage", mapID = 2195, x = 45.2, y = 67.1, faction = "N" },
            },
        },
        {
            zone = "Azsuna",
            vendors = {
                { name = "Berazus", mapID = 630, x = 47.8, y = 23.2, faction = "N" },
            },
        },
        {
            zone = "Bel'ameth",
            vendors = {
                { name = "Ellandrieth", mapID = 2369, x = 50.0, y = 45.0, faction = "N" },
                { name = "Moon Priestess Lasara", mapID = 2369, x = 55.2, y = 12.8, faction = "N" },
                { name = "Mythrin'dir", mapID = 2369, x = 62.0, y = 60.0, faction = "N" },
            },
        },
        {
            zone = "Blasted Lands",
            vendors = {
                { name = "Maurice Essman", mapID = 17, x = 45.8, y = 88.4, faction = "A" },
            },
        },
        {
            zone = "Boralus",
            vendors = {
                { name = "Pearl Barlow", mapID = 1161, x = 70.7, y = 15.7, faction = "A" },
                { name = "Provisioner Fray", mapID = 895, x = 67.5, y = 21.5, faction = "A" },
            },
        },
        {
            zone = "Borean Tundra",
            vendors = {
                { name = "Ahlurglgr", mapID = 114, x = 43.0, y = 13.8, faction = "N" },
            },
        },
        {
            zone = "Brawl'gar Arena",
            vendors = {
                { name = "\\\"Bad Luck\\\" Symmes", mapID = 6298, x = 50.0, y = 27.4, faction = "H" },
                { name = "Paul North", mapID = 503, x = 48.4, y = 29.2, faction = "H" },
            },
        },
        {
            zone = "Burning Steppes",
            vendors = {
                { name = "Hoddruc Bladebender", mapID = 36, x = 46.8, y = 44.4, faction = "N" },
            },
        },
        {
            zone = "Chamber of Heart",
            vendors = {
                { name = "MOTHER", mapID = 1473, x = 48.2, y = 72.4, faction = "N" },
            },
        },
        {
            zone = "City of Threads",
            vendors = {
                { name = "Thripps", mapID = 2213, x = 50.0, y = 31.6, faction = "N" },
            },
        },
        {
            zone = "Dalaran",
            vendors = {
                { name = "Halenthos Brightstride", mapID = 1192, x = 67.5, y = 33.9, faction = "N" },
                { name = "Val'zuun", mapID = 1192, x = 67.4, y = 62.9, faction = "N" },
            },
        },
        {
            zone = "Dalaran (Broken Isles)",
            vendors = {
                { name = "Breanni", mapID = 627, x = 58.4, y = 39.0, faction = "N" },
                { name = "Rasil Fireborne", mapID = 627, x = 43.4, y = 49.4, faction = "N" },
            },
        },
        {
            zone = "Dazar'alor",
            vendors = {
                { name = "Captain Zen'taga", mapID = 1165, x = 44.5, y = 94.4, faction = "H" },
                { name = "Provisioner Mukra", mapID = 1165, x = 51.2, y = 95.1, faction = "H" },
                { name = "T'lama", mapID = 1165, x = 32.4, y = 65.4, faction = "H" },
            },
        },
        {
            zone = "Deeprun Tram",
            vendors = {
                { name = "Quackenbush", mapID = 500, x = 53.9, y = 25.7, faction = "A" },
            },
        },
        {
            zone = "Dornogal",
            vendors = {
                { name = "Auditor Balwurz", mapID = 2339, x = 39.1, y = 24.2, faction = "N" },
                { name = "Garnett", mapID = 2339, x = 54.6, y = 57.2, faction = "N" },
                { name = "Jorid", mapID = 2339, x = 57.0, y = 60.4, faction = "N" },
                { name = "Second Chair Pawdo", mapID = 2339, x = 56.0, y = 76.4, faction = "N" },
                { name = "Velerd", mapID = 2339, x = 55.0, y = 76.6, faction = "N" },
            },
        },
        {
            zone = "Dragon Isles (Rotating)",
            vendors = {
                { name = "Celestine of the Harvest", mapID = 0, x = 0.0, y = 0.0, faction = "N" },
            },
        },
        {
            zone = "Dreadscar Rift",
            vendors = {
                { name = "Gigi Gigavoid", mapID = 1107, x = 58.4, y = 32.4, faction = "N" },
            },
        },
        {
            zone = "Dun Morogh",
            vendors = {
                { name = "Innkeeper Belm", mapID = 27, x = 54.4, y = 50.8, faction = "A" },
            },
        },
        {
            zone = "Duskwood",
            vendors = {
                { name = "Wilkinson", mapID = 47, x = 20.2, y = 58.2, faction = "A" },
            },
        },
        {
            zone = "Eastern Plaguelands",
            vendors = {
                { name = "Fiona", mapID = 23, x = 9.0, y = 66.6, faction = "N" },
            },
        },
        {
            zone = "Eversong Woods",
            vendors = {
                { name = "Apprentice Diell", mapID = 2395, x = 43.4, y = 47.4, faction = "N" },
                { name = "Armorer Goldcrest", mapID = 2395, x = 43.4, y = 47.4, faction = "N" },
                { name = "Caeris Fairdawn", mapID = 2395, x = 43.4, y = 47.4, faction = "N" },
                { name = "Neriv", mapID = 2395, x = 43.4, y = 47.4, faction = "N" },
                { name = "Ranger Allorn", mapID = 2395, x = 43.4, y = 47.4, faction = "N" },
                { name = "Sathren Azuredawn", mapID = 2395, x = 43.2, y = 47.4, faction = "N" },
            },
        },
        {
            zone = "Felwood",
            vendors = {
                { name = "Willard Harrington", mapID = 77, x = 61.6, y = 25.8, faction = "N" },
            },
        },
        {
            zone = "Founder's Point",
            vendors = {
                { name = "\\\"High Tides\\\" Ren", mapID = 2352, x = 62.4, y = 80.2, faction = "N" },
                { name = "\\\"Len\\\" Splinthoof", mapID = 2352, x = 61.6, y = 79.0, faction = "N" },
                { name = "\\\"Yen\\\" Malone", mapID = 2352, x = 62.2, y = 80.2, faction = "N" },
                { name = "Aeeshna", mapID = 2352, x = 54.4, y = 56.2, faction = "N" },
                { name = "Argan Hammerfist", mapID = 2352, x = 52.2, y = 37.8, faction = "N" },
                { name = "Balen Starfinder", mapID = 2352, x = 52.2, y = 37.8, faction = "N" },
                { name = "Brother Dovetail", mapID = 2352, x = 54.2, y = 56.2, faction = "N" },
                { name = "Faarden the Builder", mapID = 2352, x = 52.0, y = 38.4, faction = "N" },
                { name = "Harlowe Marl", mapID = 2352, x = 54.2, y = 56.2, faction = "N" },
                { name = "Hesta Forlath", mapID = 2352, x = 53.0, y = 38.2, faction = "N" },
                { name = "Klasa", mapID = 2352, x = 58.2, y = 61.6, faction = "N" },
                { name = "Pascal-K1N6", mapID = 2352, x = 54.2, y = 56.0, faction = "N" },
                { name = "The Last Architect", mapID = 2352, x = 52.6, y = 37.6, faction = "N" },
                { name = "Trevor Grenner", mapID = 2352, x = 53.5, y = 40.9, faction = "N" },
                { name = "Xiao Dan", mapID = 2352, x = 52.0, y = 38.2, faction = "N" },
            },
        },
        {
            zone = "Frostwall",
            vendors = {
                { name = "Kil'rip", mapID = 590, x = 58.6, y = 25.7, faction = "H" },
                { name = "Moz'def", mapID = 590, x = 60.0, y = 50.8, faction = "H" },
                { name = "Ribchewer", mapID = 590, x = 58.6, y = 25.7, faction = "H" },
                { name = "Sergeant Grimjaw", mapID = 590, x = 43.6, y = 47.8, faction = "H" },
                { name = "Supplymaster Eri", mapID = 590, x = 53.9, y = 41.5, faction = "H" },
                { name = "Vora Strongarm", mapID = 590, x = 51.6, y = 64.4, faction = "H" },
            },
        },
        {
            zone = "Ghostlands",
            vendors = {
                { name = "Provisioner Vredigar", mapID = 95, x = 47.4, y = 32.0, faction = "H" },
            },
        },
        {
            zone = "Gilneas",
            vendors = {
                { name = "Marie Allen", mapID = 217, x = 60.4, y = 92.3, faction = "A" },
            },
        },
        {
            zone = "Gilneas City",
            vendors = {
                { name = "Lord Candren", mapID = 217, x = 56.2, y = 13.4, faction = "A" },
                { name = "Samantha Buckley", mapID = 217, x = 65.4, y = 47.2, faction = "A" },
            },
        },
        {
            zone = "Grizzly Hills",
            vendors = {
                { name = "Woodsman Drake", mapID = 116, x = 32.4, y = 60.0, faction = "N" },
            },
        },
        {
            zone = "Hall of the Guardian",
            vendors = {
                { name = "Jackson Watkins", mapID = 735, x = 42.1, y = 55.2, faction = "N" },
            },
        },
        {
            zone = "Hallowfall",
            vendors = {
                { name = "Lars Bronsmaelt", mapID = 2215, x = 28.2, y = 56.2, faction = "N" },
                { name = "Nalina Ironsong", mapID = 2215, x = 42.8, y = 55.8, faction = "N" },
            },
        },
        {
            zone = "Harandar",
            vendors = {
                { name = "Amwa'ana", mapID = 2480, x = 56.4, y = 32.8, faction = "N" },
                { name = "Hawli", mapID = 2480, x = 59.4, y = 33.4, faction = "N" },
                { name = "Maku", mapID = 2480, x = 62.2, y = 34.6, faction = "N" },
                { name = "Mothkeeper Wew'tam", mapID = 2480, x = 45.7, y = 50.7, faction = "N" },
                { name = "Mowaia", mapID = 2480, x = 52.2, y = 54.0, faction = "N" },
                { name = "Naynar", mapID = 2413, x = 51.0, y = 50.8, faction = "N" },
            },
        },
        {
            zone = "Highmountain",
            vendors = {
                { name = "Crafty Palu", mapID = 650, x = 41.6, y = 10.4, faction = "N" },
                { name = "Torv Dubstomp", mapID = 650, x = 52.4, y = 79.8, faction = "N" },
            },
        },
        {
            zone = "Hillsbrad Foothills",
            vendors = {
                { name = "Thanthaldis Snowgleam", mapID = 25, x = 44.6, y = 46.4, faction = "A" },
            },
        },
        {
            zone = "Ironforge",
            vendors = {
                { name = "Captain Stonehelm", mapID = 87, x = 55.5, y = 47.3, faction = "A" },
                { name = "Dedric Sleetshaper", mapID = 87, x = 24.5, y = 43.7, faction = "A" },
                { name = "Inge Brightview", mapID = 87, x = 75.4, y = 9.4, faction = "A" },
            },
        },
        {
            zone = "Isle of Dorn",
            vendors = {
                { name = "Cendvin", mapID = 2248, x = 74.3, y = 45.3, faction = "N" },
                { name = "Cinnabar", mapID = 2248, x = 42.1, y = 73.0, faction = "N" },
            },
        },
        {
            zone = "K'aresh",
            vendors = {
                { name = "Om'sirik", mapID = 2472, x = 40.6, y = 29.0, faction = "N" },
                { name = "Ta'sam", mapID = 2552, x = 43.2, y = 35.2, faction = "N" },
            },
        },
        {
            zone = "Kun-Lai Summit",
            vendors = {
                { name = "Brother Furtrim", mapID = 379, x = 57.2, y = 61.0, faction = "N" },
            },
        },
        {
            zone = "Liberation of Undermine",
            vendors = {
                { name = "Ando the Gat", mapID = 2406, x = 48.1, y = 56.7, faction = "N" },
            },
        },
        {
            zone = "Loch Modan",
            vendors = {
                { name = "Drac Roughcut", mapID = 48, x = 34.8, y = 49.2, faction = "A" },
            },
        },
        {
            zone = "Lunarfall",
            vendors = {
                { name = "Krixel Pinchwhistle", mapID = 582, x = 51.2, y = 45.4, faction = "A" },
                { name = "Maaria", mapID = 582, x = 33.6, y = 50.4, faction = "A" },
                { name = "Maybell Maclure-Stonefield", mapID = 582, x = 41.2, y = 43.6, faction = "A" },
                { name = "Peter", mapID = 582, x = 52.0, y = 44.4, faction = "A" },
                { name = "Sergeant Crowler", mapID = 582, x = 37.4, y = 36.4, faction = "A" },
            },
        },
        {
            zone = "Masters' Perch",
            vendors = {
                { name = "Thraxadar", mapID = 2444, x = 39.3, y = 81.0, faction = "N" },
            },
        },
        {
            zone = "Mechagon",
            vendors = {
                { name = "Pascal-K1N6", mapID = 1462, x = 71.2, y = 32.7, faction = "N" },
                { name = "Stolen Royal Vendorbot", mapID = 1462, x = 73.6, y = 36.4, faction = "N" },
            },
        },
        {
            zone = "Nazmir",
            vendors = {
                { name = "Provisioner Lija", mapID = 863, x = 39.1, y = 79.5, faction = "H" },
            },
        },
        {
            zone = "Netherlight Temple",
            vendors = {
                { name = "Meridelle Lightspark", mapID = 702, x = 38.6, y = 23.8, faction = "N" },
            },
        },
        {
            zone = "Northern Stranglethorn",
            vendors = {
                { name = "Jaquilina Dramet", mapID = 50, x = 43.6, y = 23.0, faction = "N" },
            },
        },
        {
            zone = "Orgrimmar",
            vendors = {
                { name = "Gabbi", mapID = 85, x = 48.4, y = 81.1, faction = "H" },
                { name = "Joruh", mapID = 85, x = 38.8, y = 72.0, faction = "H" },
                { name = "Lonalo", mapID = 85, x = 58.6, y = 50.3, faction = "H" },
                { name = "Stone Guard Nargol", mapID = 85, x = 50.4, y = 58.4, faction = "H" },
            },
        },
        {
            zone = "Razorwind Shores",
            vendors = {
                { name = "\\\"High Tides\\\" Ren", mapID = 2351, x = 54.0, y = 58.0, faction = "N" },
                { name = "\\\"Len\\\" Splinthoof", mapID = 2351, x = 39.8, y = 73.2, faction = "N" },
                { name = "\\\"Yen\\\" Malone", mapID = 2351, x = 54.0, y = 58.0, faction = "N" },
                { name = "Botanist Boh'an", mapID = 2351, x = 53.6, y = 57.5, faction = "N" },
                { name = "Gronthul", mapID = 2351, x = 54.0, y = 59.0, faction = "N" },
                { name = "Hordranin", mapID = 2351, x = 54.3, y = 56.1, faction = "N" },
                { name = "Jehzar Starfall", mapID = 2351, x = 53.5, y = 58.5, faction = "N" },
                { name = "Lefton Farrer", mapID = 2351, x = 53.5, y = 58.5, faction = "N" },
                { name = "Lonomia", mapID = 2351, x = 68.2, y = 75.4, faction = "N" },
                { name = "Shon'ja", mapID = 2351, x = 54.0, y = 59.0, faction = "N" },
            },
        },
        {
            zone = "Sanctum of Light",
            vendors = {
                { name = "Eadric the Pure", mapID = 24, x = 38.9, y = 58.7, faction = "N" },
            },
        },
        {
            zone = "Searing Gorge",
            vendors = {
                { name = "Master Smith Burninate", mapID = 32, x = 38.4, y = 28.4, faction = "N" },
                { name = "Plugger Spazzring", mapID = 32, x = 34.8, y = 83.5, faction = "N" },
            },
        },
        {
            zone = "Shadowmoon Valley",
            vendors = {
                { name = "Artificer Kallaes", mapID = 539, x = 46.3, y = 39.3, faction = "N" },
            },
        },
        {
            zone = "Sholazar Basin",
            vendors = {
                { name = "Purser Boulian", mapID = 119, x = 26.8, y = 59.2, faction = "N" },
            },
        },
        {
            zone = "Silvermoon City",
            vendors = {
                { name = "Construct Ali'a", mapID = 2393, x = 55.8, y = 65.8, faction = "N" },
                { name = "Corlen Hordralin", mapID = 2393, x = 44.1, y = 62.8, faction = "N" },
                { name = "Dennia Silvertongue", mapID = 2393, x = 51.0, y = 56.5, faction = "N" },
                { name = "Dethelin", mapID = 2393, x = 52.4, y = 47.4, faction = "N" },
                { name = "Deynna", mapID = 2393, x = 48.2, y = 54.2, faction = "N" },
                { name = "Disguised Decor Duel Vendor", mapID = 2393, x = 31.7, y = 76.9, faction = "N" },
                { name = "Eriden", mapID = 2393, x = 43.6, y = 51.4, faction = "N" },
                { name = "Hesta Forlath", mapID = 2393, x = 44.2, y = 62.7, faction = "N" },
                { name = "Irodalmin", mapID = 2393, x = 48.2, y = 51.4, faction = "N" },
                { name = "Lelorian", mapID = 2393, x = 46.6, y = 51.4, faction = "N" },
                { name = "Lyna", mapID = 2393, x = 47.8, y = 53.4, faction = "N" },
                { name = "Melaris", mapID = 2393, x = 47.0, y = 51.8, faction = "N" },
                { name = "Naleidea Rivergleam", mapID = 2393, x = 52.6, y = 78.0, faction = "N" },
                { name = "Quelis", mapID = 2393, x = 56.2, y = 69.8, faction = "N" },
                { name = "Rae'ana (Silvermoon)", mapID = 2393, x = 47.7, y = 50.5, faction = "N" },
                { name = "Telemancer Astrandis", mapID = 2393, x = 52.4, y = 78.4, faction = "N" },
                { name = "Yatheon", mapID = 2393, x = 43.4, y = 53.8, faction = "N" },
                { name = "Zaralda", mapID = 2393, x = 43.2, y = 55.8, faction = "N" },
            },
        },
        {
            zone = "Silverpine Forest",
            vendors = {
                { name = "Edwin Harly", mapID = 21, x = 44.0, y = 39.8, faction = "H" },
            },
        },
        {
            zone = "Sinfall",
            vendors = {
                { name = "Chachi the Artiste", mapID = 1699, x = 54.0, y = 24.7, faction = "N" },
            },
        },
        {
            zone = "Skyhold",
            vendors = {
                { name = "Quartermaster Durnolf", mapID = 695, x = 55.5, y = 25.9, faction = "N" },
            },
        },
        {
            zone = "Spires of Arak",
            vendors = {
                { name = "Ruuan the Seer", mapID = 542, x = 46.7, y = 45.0, faction = "N" },
            },
        },
        {
            zone = "Stormshield",
            vendors = {
                { name = "Shadow-Sage Brakoss", mapID = 622, x = 44.4, y = 75.2, faction = "A" },
                { name = "Trader Caerel", mapID = 622, x = 41.6, y = 59.6, faction = "A" },
                { name = "Vindicator Nuurem", mapID = 622, x = 46.5, y = 76.6, faction = "A" },
            },
        },
        {
            zone = "Stormsong Valley",
            vendors = {
                { name = "Caspian", mapID = 942, x = 59.5, y = 69.6, faction = "A" },
            },
        },
        {
            zone = "Stormwind City",
            vendors = {
                { name = "Captain Lancy Revshon", mapID = 84, x = 67.5, y = 73.0, faction = "A" },
                { name = "Riica", mapID = 84, x = 77.8, y = 65.8, faction = "A" },
                { name = "Solelo", mapID = 84, x = 49.3, y = 80.1, faction = "A" },
                { name = "Tuuran", mapID = 84, x = 48.5, y = 68.8, faction = "A" },
            },
        },
        {
            zone = "Suramar",
            vendors = {
                { name = "First Arcanist Thalyssra", mapID = 680, x = 36.8, y = 46.6, faction = "N" },
                { name = "Jocenna", mapID = 680, x = 49.6, y = 62.8, faction = "N" },
                { name = "Leyweaver Inondra", mapID = 680, x = 40.2, y = 69.6, faction = "N" },
                { name = "Mrgrgrl", mapID = 680, x = 15.0, y = 53.4, faction = "N" },
                { name = "Mynde", mapID = 680, x = 45.6, y = 69.2, faction = "N" },
                { name = "Sileas Duskvine", mapID = 680, x = 26.2, y = 32.2, faction = "N" },
                { name = "Sundries Merchant", mapID = 680, x = 50.8, y = 77.8, faction = "N" },
            },
        },
        {
            zone = "Talador",
            vendors = {
                { name = "Duskcaller Erthix", mapID = 535, x = 70.4, y = 57.4, faction = "H" },
            },
        },
        {
            zone = "Teldrassil",
            vendors = {
                { name = "Ripley Kiefer", mapID = 57, x = 55.2, y = 89.2, faction = "A" },
            },
        },
        {
            zone = "Thaldraszus",
            vendors = {
                { name = "Ironus Coldsteel", mapID = 2025, x = 52.2, y = 80.8, faction = "N" },
            },
        },
        {
            zone = "The Azure Span",
            vendors = {
                { name = "Provisioner Aristta", mapID = 2024, x = 55.4, y = 51.4, faction = "N" },
            },
        },
        {
            zone = "The Dreamgrove",
            vendors = {
                { name = "Amurra Thistledew", mapID = 747, x = 39.8, y = 25.8, faction = "N" },
            },
        },
        {
            zone = "The Fel Hammer",
            vendors = {
                { name = "Falara Nightsong", mapID = 1519, x = 57.8, y = 44.2, faction = "N" },
            },
        },
        {
            zone = "The Forbidden Reach",
            vendors = {
                { name = "Jolinth", mapID = 2151, x = 35.2, y = 56.8, faction = "N" },
            },
        },
        {
            zone = "The Hall of Shadows",
            vendors = {
                { name = "Kelsey Steelspark", mapID = 626, x = 26.9, y = 36.8, faction = "N" },
            },
        },
        {
            zone = "The Jade Forest",
            vendors = {
                { name = "San Redscale", mapID = 371, x = 56.7, y = 44.4, faction = "N" },
            },
        },
        {
            zone = "The Maelstrom",
            vendors = {
                { name = "Flamesmith Lanying", mapID = 726, x = 30.3, y = 60.7, faction = "N" },
            },
        },
        {
            zone = "The Maw",
            vendors = {
                { name = "Ve'nari", mapID = 1543, x = 46.8, y = 41.6, faction = "N" },
            },
        },
        {
            zone = "The Ringing Deeps",
            vendors = {
                { name = "Chert", mapID = 2214, x = 43.4, y = 32.8, faction = "N" },
                { name = "Gabbun", mapID = 2214, x = 43.4, y = 33.3, faction = "N" },
                { name = "Waxmonger Squick", mapID = 2214, x = 43.0, y = 32.0, faction = "N" },
            },
        },
        {
            zone = "The Vindicaar",
            vendors = {
                { name = "Toraan the Revered", mapID = 940, x = 55.4, y = 28.6, faction = "N" },
            },
        },
        {
            zone = "The Waking Shores",
            vendors = {
                { name = "Cataloger Jakes", mapID = 2022, x = 47.0, y = 82.0, faction = "N" },
                { name = "Lifecaller Tzadrak", mapID = 2022, x = 55.0, y = 30.8, faction = "N" },
                { name = "Rae'ana (Waking Shores)", mapID = 2022, x = 47.8, y = 82.0, faction = "N" },
            },
        },
        {
            zone = "The Wandering Isle",
            vendors = {
                { name = "Caydori Brightstar", mapID = 1514, x = 50.4, y = 59.0, faction = "N" },
            },
        },
        {
            zone = "Thunder Bluff",
            vendors = {
                { name = "Brave Tuho", mapID = 88, x = 45.6, y = 55.2, faction = "H" },
            },
        },
        {
            zone = "Thunder Totem",
            vendors = {
                { name = "Ransa Greyfeather", mapID = 750, x = 38.8, y = 45.4, faction = "N" },
            },
        },
        {
            zone = "Tiragarde Sound",
            vendors = {
                { name = "Delphine", mapID = 895, x = 53.4, y = 31.2, faction = "A" },
                { name = "Janey Forrest", mapID = 1161, x = 56.3, y = 45.8, faction = "A" },
            },
        },
        {
            zone = "Trueshot Lodge",
            vendors = {
                { name = "Outfitter Reynolds", mapID = 739, x = 44.6, y = 48.4, faction = "N" },
            },
        },
        {
            zone = "Twilight Highlands",
            vendors = {
                { name = "Breana Bitterbrand", mapID = 241, x = 49.7, y = 29.6, faction = "N" },
                { name = "Craw MacGraw", mapID = 241, x = 48.6, y = 30.4, faction = "N" },
                { name = "Materialist Ophinell", mapID = 241, x = 49.8, y = 81.2, faction = "N" },
            },
        },
        {
            zone = "Undercity",
            vendors = {
                { name = "Captain Donald Adams", mapID = 90, x = 56.4, y = 90.0, faction = "H" },
            },
        },
        {
            zone = "Undermine",
            vendors = {
                { name = "Blair Bass", mapID = 2346, x = 34.1, y = 71.3, faction = "N" },
                { name = "Boatswain Hardee", mapID = 2346, x = 63.2, y = 16.2, faction = "N" },
                { name = "Lab Assistant Laszly", mapID = 2346, x = 27.5, y = 72.8, faction = "N" },
                { name = "Rocco Razzboom", mapID = 2346, x = 39.0, y = 22.0, faction = "N" },
                { name = "Shredz the Scrapper", mapID = 2346, x = 53.3, y = 72.7, faction = "N" },
                { name = "Sitch Lowdown", mapID = 2346, x = 30.4, y = 38.8, faction = "N" },
                { name = "Stacks Topskimmer", mapID = 2346, x = 43.2, y = 50.4, faction = "N" },
                { name = "Street Food Vendor", mapID = 2346, x = 26.0, y = 43.0, faction = "N" },
            },
        },
        {
            zone = "Val'sharah",
            vendors = {
                { name = "Corbin Branbell", mapID = 641, x = 42.0, y = 59.4, faction = "N" },
                { name = "Hilseth Travelstride", mapID = 641, x = 56.4, y = 80.2, faction = "N" },
                { name = "Myria Glenbrook", mapID = 641, x = 60.1, y = 84.8, faction = "N" },
                { name = "Selfira Ambergrove", mapID = 641, x = 54.3, y = 72.5, faction = "N" },
                { name = "Sylvia Hartshorn", mapID = 641, x = 54.6, y = 73.2, faction = "N" },
            },
        },
        {
            zone = "Valdrakken",
            vendors = {
                { name = "Evantkis", mapID = 2112, x = 58.2, y = 57.4, faction = "N" },
                { name = "Provisioner Thom", mapID = 2112, x = 36.4, y = 50.4, faction = "N" },
                { name = "Silvrath", mapID = 2134, x = 71.5, y = 49.7, faction = "N" },
                { name = "Tethalash", mapID = 2112, x = 25.4, y = 33.4, faction = "N" },
                { name = "Unatos", mapID = 2112, x = 58.0, y = 35.4, faction = "N" },
            },
        },
        {
            zone = "Vale of Eternal Blossoms",
            vendors = {
                { name = "Lali the Assistant", mapID = 390, x = 82.4, y = 30.4, faction = "N" },
                { name = "Sage Lotusbloom", mapID = 390, x = 62.6, y = 23.2, faction = "N" },
                { name = "Sage Whiteheart", mapID = 390, x = 86.4, y = 63.4, faction = "N" },
                { name = "Tan Shin Tiao", mapID = 390, x = 82.2, y = 29.4, faction = "N" },
            },
        },
        {
            zone = "Valley of the Four Winds",
            vendors = {
                { name = "Gina Mudclaw", mapID = 376, x = 53.2, y = 51.8, faction = "N" },
            },
        },
        {
            zone = "Voidstorm",
            vendors = {
                { name = "Chel the Chip", mapID = 2405, x = 38.8, y = 53.2, faction = "N" },
                { name = "Void Researcher Aemely", mapID = 2405, x = 52.6, y = 72.8, faction = "N" },
                { name = "Void Researcher Anomander", mapID = 2405, x = 52.6, y = 72.8, faction = "N" },
            },
        },
        {
            zone = "Warspear",
            vendors = {
                { name = "Ravenspeaker Skeega", mapID = 624, x = 53.4, y = 59.9, faction = "H" },
            },
        },
        {
            zone = "Wetlands",
            vendors = {
                { name = "Stuart Fleming", mapID = 56, x = 6.2, y = 57.4, faction = "A" },
            },
        },
        {
            zone = "Zul'Aman",
            vendors = {
                { name = "Depthdiver Tu'nakit", mapID = 2568, x = 68.2, y = 20.2, faction = "N" },
                { name = "Kuvahn", mapID = 2568, x = 45.2, y = 69.8, faction = "N" },
                { name = "Magovu", mapID = 2437, x = 45.8, y = 65.8, faction = "N" },
                { name = "Tajaka Sawtusk", mapID = 2568, x = 46.0, y = 66.0, faction = "N" },
            },
        },
        {
            zone = "Zuldazar",
            vendors = {
                { name = "Arcanist Peroleth", mapID = 862, x = 58.0, y = 62.5, faction = "H" },
            },
        },
    },
}
